### ISSUE TITLE
Flag selectable does not work on tap, instead on long press

### ISSUE THREAD

**Issue by famictech2000** [MojtabaHs/iPhoneNumberField#9] opened 2020-12-24 04:40 UTC
When I tap on the flag, nothing happens; instead if I long press the flag, then the sheet appears to select a country flag/country code.

**Comment by MojtabaHs** [comment] 2021-02-05 17:55
I can't reproduce your issue. But I guess that you are using the field inside something intractable that delays the touch so you should hold your touch. Please upload a sample with your issue.

**Comment by MojtabaHs** [comment] 2021-02-05 18:25
I'm going to close this since it is not reproducible. Feel free to reopen this when you upload your instructions or sample project.

**Closed by MojtabaHs** 2021-02-05 18:25 UTC

**Comment by rawmean** [comment] 2022-02-10 02:22
I'm using the field inside a `Form` (SwiftUI) and I have a similar problem. I don't think `Form` delays touch

**Comment by griebs23** [comment] 2024-01-15 20:23
I had the same problem. A hideKeyboard onTapGesture was applied to containing Zstack. Moved it around and fixed.
